### PR TITLE
fix PrintPreview and Print

### PR DESCRIPTION
**Pull request by AmirrezaFiroozi**
added import statement for QPrint() preventing the crash when clicked on the File --> Print Preview / Print
I also applied the changes you did in the PKGBUILD, hence you will need to change the PKGBUILD and delete the 3 modifications previously made in the build function :)

### CODE REVIEW

**Comment by purboo** [comment]
Hi, @AmirrezaFiroozi , thanks for the commits. 

However, the changes you made would result in the incompatibility on distros (e.g., Ubuntu 18.04) which does not have the latest PyQt5 version. So, I think if you are using Arch it is better to do the changes in the PKGBUILD file.

**Comment by AmirrezaFiroozi** [comment]
Hi, @purboo, thank you for the information :) 
Adding the following line to the PKGBUILD file should do the trick.
sed -i '29i from PyQt5.QtPrintSupport import * ' ldoce5viewer/qtgui/main.py

**Comment by purboo** [comment]
@AmirrezaFiroozi , thank you for the info. I have updated this github project with the changes you made without the sip part. I have also updated the aur PKGBUILD. Now the printing should work.

**Comment by AmirrezaFiroozi** [comment]
@purboo, You are welcome and thank you for fixing the issue:)

**Pull request closed without merging**
